# Generated by Django 3.0.7 on 2025-04-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaGV', models.CharField(max_length=10, unique=True)),
                ('HoTen', models.CharField(max_length=100)),
                ('SoDT', models.CharField(blank=True, max_length=15, null=True)),
                ('VAI_TRO', models.CharField(choices=[('admin', 'Admin'), ('ban_giam_hieu', 'Ban Giám Hiệu'), ('giao_vien', 'Giáo Viên')], default='giao_vien', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GIAOVIEN',
            },
        ),
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaHS', models.CharField(max_length=15, unique=True)),
                ('HoTen', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('GTinh', models.CharField(max_length=5)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('SoDT', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'HOCSINH',
            },
        ),
        migrations.CreateModel(
            name='HocSinhLop',
            fields=[
                ('HSID', models.AutoField(primary_key=True, serialize=False)),
                ('NamHOC', models.CharField(max_length=15)),
                ('MaHS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.HocSinh')),
            ],
            options={
                'db_table': 'HOCSINH_LOP',
            },
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('MaLOP', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TenLOP', models.CharField(max_length=15)),
                ('NamHOC', models.CharField(max_length=15)),
                ('Khoi', models.IntegerField()),
                ('GVCN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.GiaoVien')),
            ],
            options={
                'db_table': 'LOPHOC',
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('MaMH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenMH', models.CharField(max_length=50)),
                ('SoTiet', models.IntegerField()),
                ('KieuDG', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'MONHOC',
            },
        ),
        migrations.CreateModel(
            name='PhuHuynh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaPH', models.CharField(max_length=10, unique=True)),
                ('HoTen', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('SoDT', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PHUHUYNH',
            },
        ),
        migrations.CreateModel(
            name='YKien',
            fields=[
                ('YKID', models.AutoField(primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('ThoiGianGui', models.DateTimeField(auto_now_add=True)),
                ('TrangThai', models.CharField(max_length=20)),
                ('MaHS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.HocSinh')),
                ('MaPH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.PhuHuynh')),
            ],
            options={
                'db_table': 'YKIEN',
            },
        ),
        migrations.CreateModel(
            name='MonHocLop',
            fields=[
                ('MaMHL', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NamHOC', models.CharField(max_length=10)),
                ('MaGV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.GiaoVien')),
                ('MaLOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.LopHoc')),
                ('MaMH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.MonHoc')),
            ],
            options={
                'db_table': 'MONHOC_LOP',
            },
        ),
        migrations.CreateModel(
            name='KetQua',
            fields=[
                ('kqid', models.AutoField(primary_key=True, serialize=False)),
                ('nam_hoc', models.CharField(max_length=10)),
                ('hk1_tx1', models.FloatField(blank=True, null=True)),
                ('hk1_tx2', models.FloatField(blank=True, null=True)),
                ('hk1_tx3', models.FloatField(blank=True, null=True)),
                ('hk1_tx4', models.FloatField(blank=True, null=True)),
                ('hk1_gk', models.FloatField(blank=True, null=True)),
                ('hk1_ck', models.FloatField(blank=True, null=True)),
                ('hk2_tx1', models.FloatField(blank=True, null=True)),
                ('hk2_tx2', models.FloatField(blank=True, null=True)),
                ('hk2_tx3', models.FloatField(blank=True, null=True)),
                ('hk2_tx4', models.FloatField(blank=True, null=True)),
                ('hk2_gk', models.FloatField(blank=True, null=True)),
                ('hk2_ck', models.FloatField(blank=True, null=True)),
                ('hsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.HocSinhLop')),
                ('ma_mhl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.MonHocLop')),
            ],
            options={
                'db_table': 'KETQUA',
            },
        ),
        migrations.AddField(
            model_name='hocsinhlop',
            name='MaLOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.LopHoc'),
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='MaPH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.PhuHuynh'),
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HocBa',
            fields=[
                ('HBID', models.AutoField(primary_key=True, serialize=False)),
                ('NamHOC', models.CharField(max_length=10)),
                ('XepLoaiHK1_HL', models.CharField(max_length=10)),
                ('XepLoaiHK2_HL', models.CharField(max_length=10)),
                ('XepLoaiHK1_RL', models.CharField(max_length=10)),
                ('XepLoaiHK2_RL', models.CharField(max_length=10)),
                ('HSID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.HocSinhLop')),
            ],
            options={
                'db_table': 'HOCBA',
            },
        ),
        migrations.CreateModel(
            name='YKienGV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaGV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.GiaoVien')),
                ('YKID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.YKien')),
            ],
            options={
                'db_table': 'YKIEN_GV',
                'unique_together': {('YKID', 'MaGV')},
            },
        ),
    ]
