# Generated by Django 3.0.7 on 2025-04-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketqua',
            name='hk1_nx1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk1_nx2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk1_nxck',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk1_nxgk',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk1_tx5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk2_nx1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk2_nx2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk2_nxck',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk2_nxgk',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='hk2_tx5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monhoclop',
            name='ChoPhepNhapDiem',
            field=models.BooleanField(default=True),
        ),
    ]
